### PR TITLE
Include templates and static into installed package, fix typo

### PR DESCRIPTION
**Pull request by rassie**
We finally started integrating `django-etherpadlite` into our app and found two bugs:
1. `setup.py` didn't include either templates or static files (my bad!)
2. `padSessionId` is checked for, but `sessionId` is used.

Patches are small, perhaps you can accept them in this batch.

### CODE REVIEW

**Comment by leylaso** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

On 02/04/12 05:38 PM, Nikolai Prokoschenko wrote:

> 1. `padSessionId` is checked for, but `sessionId` is used.
>    This is deliberate - sessionId will sometimes be set on a cross-domain
>    cookie, so I worked around it by using the same value for both cookies...

---

Sofian Benaissa :: Koumbit.org
514-907-9494 ext. 210 :: sofian@koumbit.org

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1.4.10 (GNU/Linux)
Comment: Using GnuPG with Mozilla - http://enigmail.mozdev.org/

iEYEARECAAYFAk96G+IACgkQLKnFWUVKAB9qLACg5LgoeMSlZmAw1TZPmMriI852
q4IAoKJPloQuO6PIqTYd9RPMy1bbgCEp
=t0wM
-----END PGP SIGNATURE-----

**Comment by rassie** [comment]
Oh, then I've got an integration bug somewhere, since I've had an error message complaining about missing sessionId. Gotta look into that, thanks for the pointer.

**Comment by leylaso** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

On 02/04/12 05:50 PM, Nikolai Prokoschenko wrote:

> Oh, then I've got an integration bug somewhere, since I've had an error
> message complaining about missing sessionId. Gotta look into that,
> thanks for the pointer.
> I had to set a SESSION_COOKIE_DOMAIN in settings.py and serve the
> etherpad server from the same domain as the client to get things
> working properly.

---

Sofian Benaissa :: Koumbit.org
514-907-9494 ext. 210 :: sofian@koumbit.org

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1.4.10 (GNU/Linux)
Comment: Using GnuPG with Mozilla - http://enigmail.mozdev.org/

iEYEARECAAYFAk96UOMACgkQLKnFWUVKAB+TpwCfaMZzafmJaFwfD50hS3PIcs8e
IqEAnA+qNCeqXEwZFpLQ8WsRZehDPfGk
=HEns
-----END PGP SIGNATURE-----

**Comment by rassie** [comment]
Somehow, GitHub pulls everything I commit into this pull request, I'll open another one (or two or three ;-)).

**Pull request closed without merging**
