### PR TITLE
Introduce setup.py

### PR DESCRIPTION
**Pull request by rassie**
Mostly fix for missing setup.py (see #1), however also a bit of cleanup.

### CODE REVIEW

**Comment by leylaso** [comment]
I originally planned to do this when I was closer to an actual release. I am not sure that things like the module name, etc... won't change along the way.

Also I depend heavily on pycurl to talk to the etherpad service - without it this module won't do you much good...

**Comment by leylaso** [comment]
And part of what I feel is important to any release is tests, which this module will get

**Comment by rassie** [comment]
I don't want to pressure you into something that does not fit well into your plans. I've still got my fork and can control what goes in and what stays out.

Having said that, my stance is quite simple and it's probably similar to many others': I'm integrating Etherpad-lite into our product and wanted to make use of some module, so I wouldn't need to reimplement all the stuff it'd already do. I'm perfectly aware of the pre-alpha stage of your module and I'm also ready to adapt my code as the upstream changes and  to contribute patches if needed. However, one thing I desperately need to work with it is installability through my project's `setup.py` and/or `pip`, which is currently not possible at all.

That's why I'd introduce `setup.py` this early in the project -- the module is now installable and usable directly from the clone directory (`setup.py develop`) . And speaking of tests: running them as `setup.py test` is usually a good start ;-)

`pycurl` dependency is tricky, I'm well aware of the fact that it's needed, however, it doesn't seem to be installable on my system (SLE11) (compiles against `/usr/lib64/libcurl.a`, which I don't have). I'm going to google a bit more on how to tackle this problem.

**Comment by leylaso** [comment]
Sorry, I should have said I will hold off on this until I have got things a little more stable on my end - in a couple of weeks I should be ready to pull this in. I appreciate your interest.

Looking forward to hearing about your solution for the `pycurl` dependency on SLE11

**Comment by rassie** [comment]
I'm curious myself :-)

**Pull request merged**
